import type { Profession } from "./types";
import { APPEARANCE, COMMON_TAIL } from "./universal";

const BAR_LEVELS = [
  "Barista",
  "Bartender",
  "Senior Bartender",
  "Head Bartender",
  "Bar Supervisor",
  "Bar Manager",
  "Beverage Manager",
] as const;

const SENIOR = new Set<string>([
  "Senior Bartender",
  "Head Bartender",
  "Bar Supervisor",
  "Bar Manager",
  "Beverage Manager",
]);

/** Параметры бармена и бариста — по документу заказчика «Bar & Barista». */
export const bar: Profession = {
  id: "bar",
  title: "Bartender / Barista",
  family: "service",
  blurb: "Bar scale, cocktails, cost control, responsible serving.",
  levels: BAR_LEVELS,
  questions: [
    {
      id: "level",
      ask: "Your most recent position behind the bar?",
      label: "Position",
      kind: "single",
      slot: "summary",
      options: BAR_LEVELS,
      required: true,
    },
    {
      id: "years",
      ask: "How many years of bar or coffee experience?",
      label: "Experience",
      kind: "number",
      slot: "experience",
      unit: "years",
      min: 0,
      max: 40,
      required: true,
    },
    {
      id: "venue_types",
      ask: "What kind of venues were they?",
      label: "Venue types",
      kind: "multi",
      slot: "specifics",
      options: [
        "Fine dining restaurant",
        "Luxury bar / lounge",
        "Beach club",
        "Nightclub",
        "Hotel bar",
        "High-volume venue",
        "Specialty coffee",
      ],
      required: true,
    },
    {
      id: "bar_stations",
      ask: "How many bar stations did the bar have?",
      label: "Bar stations",
      kind: "number",
      slot: "scale",
      unit: "stations",
      min: 0,
      max: 30,
      required: true,
    },
    {
      id: "guests_per_shift",
      ask: "How many guests did you serve per shift on an average night?",
      label: "Guests per shift",
      kind: "number",
      slot: "scale",
      unit: "guests",
      min: 0,
      max: 3000,
      required: true,
    },
    {
      id: "peak_volume",
      ask: "What do peak days look like: weekends, events?",
      label: "Peak volume",
      kind: "text",
      slot: "scale",
      hint: "For example: 400 guests on Friday, private events of up to 1,000.",
    },
    {
      id: "revenue",
      ask: "What was the bar revenue per shift or per month?",
      label: "Bar revenue",
      kind: "text",
      slot: "scale",
      hint: "Managers only; skip it if you did not own the numbers.",
      showIf: (a) => typeof a.level === "string" && SENIOR.has(a.level),
    },
    {
      id: "alcohol",
      ask: "Which alcohol areas do you work with?",
      label: "Alcohol",
      kind: "multi",
      slot: "skills",
      options: [
        "Classic cocktails",
        "Signature cocktails",
        "Whisky",
        "Rum",
        "Gin",
        "Tequila",
        "Wine",
        "Champagne",
      ],
    },
    {
      id: "non_alcoholic",
      ask: "And on the non-alcoholic side?",
      label: "Non-alcoholic",
      kind: "multi",
      slot: "skills",
      options: ["Mocktails", "Coffee", "Juice / wellness concepts"],
    },
    {
      id: "inventory",
      ask: "Did you run inventory and cost control? Which numbers did you track?",
      label: "Inventory and cost control",
      kind: "multi",
      slot: "specifics",
      options: [
        "Stock counts (daily / weekly)",
        "Pour cost",
        "Beverage cost",
        "Shrinkage control",
      ],
      required: true,
    },
    {
      id: "pos_systems",
      ask: "Which POS and inventory systems have you used?",
      label: "Systems",
      kind: "multi",
      slot: "systems",
      options: [
        "Micros / Oracle Simphony",
        "Lightspeed",
        "Toast",
        "Square",
        "iiko",
        "r_keeper",
        "Inventory software",
        "Recipe costing tools",
        "Other",
      ],
      required: true,
    },
    {
      id: "team_size",
      ask: "How many bartenders did you manage?",
      label: "Bartenders managed",
      kind: "number",
      slot: "scale",
      unit: "people",
      min: 0,
      max: 100,
      showIf: (a) => typeof a.level === "string" && SENIOR.has(a.level),
    },
    {
      id: "team_duties",
      ask: "What did you do for the team?",
      label: "Team duties",
      kind: "multi",
      slot: "specifics",
      options: [
        "Shift scheduling",
        "Training and onboarding",
        "SOP enforcement",
      ],
      showIf: (a) => typeof a.level === "string" && SENIOR.has(a.level),
    },
    {
      id: "compliance",
      ask: "Which alcohol compliance rules have you worked under?",
      label: "Alcohol compliance",
      kind: "multi",
      slot: "specifics",
      options: [
        "Responsible serving",
        "Local alcohol regulations",
        "Age control",
        "Brand standards",
      ],
      required: true,
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
