import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/**
 * Параметры шефа.
 *
 * Заказчица голосом: «я давала вопросы, где мы чётко определяем не скиллы,
 * а специфику этого шефа. Есть которые работали в кейтеринге, в fine dining,
 * в casual dining, у них специальные техники — grill, cold section — нужно
 * определить, какая у него».
 *
 * Отсюда section_experience и techniques: это не «навыки» галочками, а разрез
 * опыта, по которому шефа реально отбирают на позицию.
 */

const SECTIONS = [
  "Garde manger / Cold section",
  "Grill",
  "Saute",
  "Butcher",
  "Fish",
  "Pastry",
  "Bakery",
  "Larder",
  "Pass",
  "Prep / CPU",
] as const;

/** Уровни, на которых уже отвечают за деньги и меню, а не только за станцию. */
const SENIOR_LEVELS = [
  "Sous Chef",
  "Senior Sous Chef",
  "Head Chef",
  "Executive Chef",
  "Executive Pastry Chef",
];

export const chef: Profession = {
  id: "chef",
  title: "Chef",
  family: "kitchen",
  blurb: "Kitchen, sections, techniques, menu, food cost.",
  levels: [
    "Commis Chef",
    "Demi Chef de Partie",
    "Chef de Partie",
    "Junior Sous Chef",
    "Sous Chef",
    "Senior Sous Chef",
    "Head Chef",
    "Executive Chef",
    "Executive Pastry Chef",
  ],
  questions: [
    {
      id: "level",
      ask: "What is your level in the kitchen?",
      label: "Position level",
      kind: "single",
      slot: "summary",
      options: [
        "Commis Chef",
        "Demi Chef de Partie",
        "Chef de Partie",
        "Junior Sous Chef",
        "Sous Chef",
        "Senior Sous Chef",
        "Head Chef",
        "Executive Chef",
        "Executive Pastry Chef",
      ],
      required: true,
      hint: "The level decides what we ask next.",
    },
    {
      id: "years",
      ask: "How many years in the kitchen?",
      label: "Experience",
      kind: "number",
      slot: "experience",
      unit: "years",
      min: 0,
      max: 50,
      required: true,
    },
    {
      id: "cuisines",
      ask: "Which cuisines do you know?",
      label: "Cuisines",
      kind: "multi",
      slot: "specifics",
      options: [
        "French",
        "Italian",
        "Mediterranean",
        "Pan-Asian",
        "Japanese",
        "Chinese",
        "Indian",
        "Middle Eastern",
        "Levantine",
        "Kazakh",
        "Georgian",
        "Turkish",
        "Modern European",
        "Pastry & Bakery",
        "Steakhouse",
        "Seafood",
        "Vegan / Plant-based",
      ],
      required: true,
    },
    {
      id: "operation_types",
      ask: "What kinds of operations have you worked in?",
      label: "Operation types",
      kind: "multi",
      slot: "specifics",
      options: [
        "Fine dining",
        "Casual dining",
        "Catering",
        "Banqueting",
        "Hotel kitchen",
        "Resort",
        "Central production / CPU",
        "QSR",
        "Cloud kitchen",
        "Cruise",
        "Events",
      ],
      required: true,
      hint: "Catering and fine dining are different jobs, and this is the first thing an employer looks at.",
    },
    {
      id: "section_experience",
      ask: "Which sections have you worked?",
      label: "Sections",
      kind: "multi",
      slot: "specifics",
      options: [...SECTIONS, "Banquet line"],
      required: true,
    },
    {
      id: "main_section",
      ask: "Which section is your main one, where you are strongest?",
      label: "Main section",
      kind: "single",
      slot: "specifics",
      options: SECTIONS,
      required: true,
      showIf: (a) =>
        Array.isArray(a.section_experience) && a.section_experience.length > 0,
    },
    {
      id: "techniques",
      ask: "Which techniques do you use?",
      label: "Techniques",
      kind: "multi",
      slot: "skills",
      options: [
        "Sous-vide",
        "Josper / charcoal",
        "Smoking",
        "Fermentation",
        "Curing",
        "Butchery",
        "Fish filleting",
        "Pasta making",
        "Bread & viennoiserie",
        "Chocolate & sugar work",
        "Plating & garnish",
        "Molecular",
      ],
    },
    {
      id: "venue_types",
      ask: "What kind of venues was this in?",
      label: "Venue types",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "covers",
      ask: "How many covers did the kitchen serve per shift?",
      label: "Covers per shift",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 10000,
      required: true,
    },
    {
      id: "team_size",
      ask: "How many people reported to you?",
      label: "Team",
      kind: "number",
      slot: "scale",
      unit: "people",
      min: 0,
      max: 500,
      required: true,
      // Комми ни за кем не смотрит — вопрос ему не задаём.
      showIf: (a) => a.level !== "Commis Chef",
    },
    {
      id: "menu_development",
      ask: "Did you develop menus? Tell us what exactly was on you.",
      label: "Menu development",
      kind: "text",
      slot: "specifics",
      showIf: (a) =>
        a.level !== "Commis Chef" && a.level !== "Demi Chef de Partie",
      hint: "Seasonal updates, tasting menus, menu engineering.",
    },
    {
      id: "food_cost",
      ask: "Were you responsible for food cost? What percentage did you hold?",
      label: "Food cost",
      kind: "text",
      slot: "specifics",
      showIf: (a) =>
        typeof a.level === "string" && SENIOR_LEVELS.includes(a.level),
    },
    {
      id: "opening_experience",
      ask: "Have you opened a venue from scratch?",
      label: "Opening experience",
      kind: "single",
      slot: "specifics",
      options: ["Yes, I led the opening", "Yes, I took part", "No"],
      required: true,
    },
    {
      id: "haccp",
      ask: "How are you with HACCP and food safety?",
      label: "HACCP / Food safety",
      kind: "single",
      slot: "skills",
      options: [
        "Certified, and I set up the system",
        "Certified",
        "Worked to the standard",
        "No experience",
      ],
      required: true,
    },
    {
      /**
       * Правка Алдияра: «Для шефов фото блюд, с возможностью добавить много
       * фоток с телефона одним заходом».
       */
      id: "dish_photos",
      ask: "Upload photos of your dishes: this is a chef portfolio, and it gets looked at before any text.",
      label: "Dish photos",
      kind: "photos",
      slot: "portfolio",
      required: true,
      hint: "You can pick many shots at once, they upload in one go.",
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
