import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры хостес — по списку из документа заказчика, раздел 1.1. */
export const hostess: Profession = {
  id: "hostess",
  title: "Hostess",
  family: "service",
  blurb: "Встреча гостей, бронирование, работа с VIP.",
  levels: [
    "Hostess",
    "Senior Hostess",
    "Head Hostess",
    "Guest Relations Officer",
  ],
  questions: [
    {
      id: "level",
      ask: "На какой позиции вы работали последней?",
      label: "Позиция",
      kind: "single",
      slot: "summary",
      options: [
        "Hostess",
        "Senior Hostess",
        "Head Hostess",
        "Guest Relations Officer",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "Сколько лет вы в этой роли?",
      label: "Опыт",
      kind: "number",
      slot: "experience",
      unit: "лет",
      min: 0,
      max: 40,
      required: true,
    },
    {
      id: "venue_types",
      ask: "В каких заведениях работали? Можно несколько.",
      label: "Типы заведений",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "covers",
      ask: "Сколько covers в смену проходило через зал?",
      label: "Covers за смену",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 5000,
      required: true,
      hint: "Примерно — важен порядок, а не точность.",
    },
    {
      id: "reservation_systems",
      ask: "С какими системами бронирования работали?",
      label: "Системы бронирования",
      kind: "multi",
      slot: "systems",
      options: [
        "OpenTable",
        "SevenRooms",
        "Quandoo",
        "ResDiary",
        "Tock",
        "Bookatable",
        "Собственная система",
        "Только журнал",
      ],
      required: true,
    },
    {
      id: "guest_relations",
      ask: "Расскажите про работу с гостем: жалобы, лист ожидания, посадка. Что было на вас?",
      label: "Guest relations",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "Можно надиктовать — ИИ сам разложит это по пунктам.",
    },
    {
      id: "vip_experience",
      ask: "Был опыт с VIP-гостями?",
      label: "VIP-гости",
      kind: "single",
      slot: "specifics",
      options: ["Постоянно", "Регулярно", "Иногда", "Нет"],
      required: true,
    },
    {
      id: "vip_details",
      ask: "Что именно входило в работу с VIP?",
      label: "VIP — детали",
      kind: "text",
      slot: "specifics",
      showIf: (a) =>
        a.vip_experience === "Постоянно" || a.vip_experience === "Регулярно",
    },
    {
      id: "shift_types",
      ask: "Какие смены вам подходят?",
      label: "График",
      kind: "multi",
      slot: "summary",
      options: [
        "Morning",
        "Evening",
        "Split shift",
        "Night",
        "Weekends",
        "Rotating",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
