import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры хостес — по списку из документа заказчика, раздел 1.1. */
export const hostess: Profession = {
  id: "hostess",
  title: "Hostess",
  family: "service",
  blurb: "Greeting guests, reservations, VIP care.",
  levels: [
    "Hostess",
    "Senior Hostess",
    "Head Hostess",
    "Guest Relations Officer",
  ],
  questions: [
    {
      id: "level",
      ask: "What was your most recent position?",
      label: "Position",
      kind: "single",
      slot: "summary",
      options: [
        "Hostess",
        "Senior Hostess",
        "Head Hostess",
        "Guest Relations Officer",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "How many years have you been in this role?",
      label: "Experience",
      kind: "number",
      slot: "experience",
      unit: "years",
      min: 0,
      max: 40,
      required: true,
    },
    {
      id: "venue_types",
      ask: "What venues have you worked in? Pick as many as apply.",
      label: "Venue types",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "covers",
      ask: "How many covers went through the room per shift?",
      label: "Covers per shift",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 5000,
      required: true,
      hint: "Roughly: the order of magnitude matters, not the exact number.",
    },
    {
      id: "reservation_systems",
      ask: "Which reservation systems have you used?",
      label: "Reservation systems",
      kind: "multi",
      slot: "systems",
      options: [
        "OpenTable",
        "SevenRooms",
        "Quandoo",
        "ResDiary",
        "Tock",
        "Bookatable",
        "In-house system",
        "Paper book only",
      ],
      required: true,
    },
    {
      id: "guest_relations",
      ask: "Tell us about guest relations: complaints, waitlist, seating. What was on you?",
      label: "Guest relations",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "You can dictate it, the AI will break it into points.",
    },
    {
      id: "vip_experience",
      ask: "Any experience with VIP guests?",
      label: "VIP guests",
      kind: "single",
      slot: "specifics",
      options: ["Constantly", "Regularly", "Sometimes", "No"],
      required: true,
    },
    {
      id: "vip_details",
      ask: "What exactly did VIP work involve?",
      label: "VIP details",
      kind: "text",
      slot: "specifics",
      showIf: (a) =>
        a.vip_experience === "Constantly" || a.vip_experience === "Regularly",
    },
    {
      id: "shift_types",
      ask: "Which shifts work for you?",
      label: "Schedule",
      kind: "multi",
      slot: "summary",
      options: [
        "Morning",
        "Evening",
        "Split shift",
        "Night",
        "Weekends",
        "Rotating",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
