import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры менеджера — по списку из документа заказчика, раздел 1.1. */
export const manager: Profession = {
  id: "manager",
  title: "Manager",
  family: "management",
  blurb: "Операции, команда, бюджет, открытия.",
  levels: [
    "Supervisor",
    "Assistant Manager",
    "Restaurant Manager",
    "General Manager",
    "Operations Manager",
    "F&B Manager",
    "Area / Cluster Manager",
  ],
  questions: [
    {
      id: "level",
      ask: "Какая у вас управленческая позиция?",
      label: "Позиция",
      kind: "single",
      slot: "summary",
      options: [
        "Supervisor",
        "Assistant Manager",
        "Restaurant Manager",
        "General Manager",
        "Operations Manager",
        "F&B Manager",
        "Area / Cluster Manager",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "Сколько лет в управлении?",
      label: "Опыт",
      kind: "number",
      slot: "experience",
      unit: "лет",
      min: 0,
      max: 45,
      required: true,
    },
    {
      id: "operation_types",
      ask: "Какого типа операциями управляли?",
      label: "Тип операций",
      kind: "multi",
      slot: "specifics",
      options: [
        "Standalone restaurant",
        "Hotel F&B",
        "Resort",
        "Restaurant group / chain",
        "Catering",
        "Banqueting & events",
        "QSR",
        "Bar / Nightlife",
        "Cafe chain",
      ],
      required: true,
    },
    {
      id: "outlets",
      ask: "Сколько точек было под вашим управлением?",
      label: "Outlets",
      kind: "number",
      slot: "scale",
      unit: "шт.",
      min: 1,
      max: 200,
      required: true,
    },
    {
      id: "team_size",
      ask: "Какого размера была команда?",
      label: "Размер команды",
      kind: "number",
      slot: "scale",
      unit: "чел.",
      min: 0,
      max: 2000,
      required: true,
    },
    {
      id: "direct_reports",
      ask: "А сколько человек подчинялись напрямую?",
      label: "Прямое подчинение",
      kind: "number",
      slot: "scale",
      unit: "чел.",
      min: 0,
      max: 200,
      required: true,
    },
    {
      id: "covers",
      ask: "Сколько covers в день проходило через заведение?",
      label: "Covers в день",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 20000,
      required: true,
    },
    {
      id: "revenue",
      ask: "Какой оборот вы вели? Укажите валюту и период.",
      label: "Оборот",
      kind: "text",
      slot: "scale",
      required: true,
      hint: "Например: 3.2M USD в год, или 25M KZT в месяц.",
    },
    {
      id: "venue_types",
      ask: "В заведениях какого типа это было?",
      label: "Типы заведений",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "opening_experience",
      ask: "Открывали заведения с нуля?",
      label: "Opening experience",
      kind: "single",
      slot: "specifics",
      options: ["Да, вёл открытие", "Да, участвовал", "Нет"],
      required: true,
    },
    {
      id: "openings_count",
      ask: "Сколько открытий на вашем счету?",
      label: "Открытий",
      kind: "number",
      slot: "scale",
      unit: "шт.",
      min: 1,
      max: 100,
      showIf: (a) =>
        a.opening_experience === "Да, вёл открытие" ||
        a.opening_experience === "Да, участвовал",
    },
    {
      id: "staff_management",
      ask: "Расскажите про работу с командой: графики, дисциплина, текучка. Что было на вас?",
      label: "Staff management",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "Можно надиктовать — ИИ разложит на пункты.",
    },
    {
      id: "recruitment",
      ask: "Занимались наймом сами?",
      label: "Recruitment",
      kind: "single",
      slot: "specifics",
      options: [
        "Да, полный цикл",
        "Да, финальное решение",
        "Участвовал",
        "Нет",
      ],
      required: true,
    },
    {
      id: "training",
      ask: "Обучение персонала — вели, внедряли программы?",
      label: "Training",
      kind: "text",
      slot: "specifics",
      hint: "Стандарты сервиса, аттестации, обучение новичков.",
    },
    {
      id: "budgeting",
      ask: "За какие показатели P&L вы отвечали?",
      label: "Budgeting",
      kind: "multi",
      slot: "skills",
      options: [
        "Revenue / sales",
        "Food cost",
        "Beverage cost",
        "Labour cost",
        "Полный P&L",
        "CAPEX",
        "Закупки",
        "Инвентаризация",
      ],
      required: true,
    },
    {
      id: "reporting",
      ask: "В каких системах вели отчётность?",
      label: "Reporting",
      kind: "multi",
      slot: "systems",
      options: [
        "Micros / Oracle",
        "iiko",
        "r_keeper",
        "Opera PMS",
        "Excel / Google Sheets",
        "Power BI",
        "Собственная система",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
