import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры менеджера — по списку из документа заказчика, раздел 1.1. */
export const manager: Profession = {
  id: "manager",
  title: "Manager",
  family: "management",
  blurb: "Operations, team, budget, openings.",
  levels: [
    "Supervisor",
    "Assistant Manager",
    "Restaurant Manager",
    "General Manager",
    "Operations Manager",
    "F&B Manager",
    "Area / Cluster Manager",
  ],
  questions: [
    {
      id: "level",
      ask: "What is your management position?",
      label: "Position",
      kind: "single",
      slot: "summary",
      options: [
        "Supervisor",
        "Assistant Manager",
        "Restaurant Manager",
        "General Manager",
        "Operations Manager",
        "F&B Manager",
        "Area / Cluster Manager",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "How many years in management?",
      label: "Experience",
      kind: "number",
      slot: "experience",
      unit: "years",
      min: 0,
      max: 45,
      required: true,
    },
    {
      id: "operation_types",
      ask: "What kind of operations did you manage?",
      label: "Operation type",
      kind: "multi",
      slot: "specifics",
      options: [
        "Standalone restaurant",
        "Hotel F&B",
        "Resort",
        "Restaurant group / chain",
        "Catering",
        "Banqueting & events",
        "QSR",
        "Bar / Nightlife",
        "Cafe chain",
      ],
      required: true,
    },
    {
      id: "outlets",
      ask: "How many outlets did you manage?",
      label: "Outlets",
      kind: "number",
      slot: "scale",
      unit: "units",
      min: 1,
      max: 200,
      required: true,
    },
    {
      id: "team_size",
      ask: "How large was the team?",
      label: "Team size",
      kind: "number",
      slot: "scale",
      unit: "people",
      min: 0,
      max: 2000,
      required: true,
    },
    {
      id: "direct_reports",
      ask: "And how many reported to you directly?",
      label: "Direct reports",
      kind: "number",
      slot: "scale",
      unit: "people",
      min: 0,
      max: 200,
      required: true,
    },
    {
      id: "covers",
      ask: "How many covers a day went through the venue?",
      label: "Covers per day",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 20000,
      required: true,
    },
    {
      id: "revenue",
      ask: "What revenue did you run? Give the currency and the period.",
      label: "Revenue",
      kind: "text",
      slot: "scale",
      required: true,
      hint: "For example: 3.2M USD a year, or 25M KZT a month.",
    },
    {
      id: "venue_types",
      ask: "What kind of venues was this in?",
      label: "Venue types",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "opening_experience",
      ask: "Have you opened venues from scratch?",
      label: "Opening experience",
      kind: "single",
      slot: "specifics",
      options: ["Yes, I led the opening", "Yes, I took part", "No"],
      required: true,
    },
    {
      id: "openings_count",
      ask: "How many openings have you done?",
      label: "Openings",
      kind: "number",
      slot: "scale",
      unit: "units",
      min: 1,
      max: 100,
      showIf: (a) =>
        a.opening_experience === "Yes, I led the opening" ||
        a.opening_experience === "Yes, I took part",
    },
    {
      id: "staff_management",
      ask: "Tell us about managing the team: rotas, discipline, turnover. What was on you?",
      label: "Staff management",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "You can dictate it, the AI will break it into points.",
    },
    {
      id: "recruitment",
      ask: "Did you hire people yourself?",
      label: "Recruitment",
      kind: "single",
      slot: "specifics",
      options: [
        "Yes, end to end",
        "Yes, the final call",
        "I took part",
        "No",
      ],
      required: true,
    },
    {
      id: "training",
      ask: "Staff training: did you run it, did you build programmes?",
      label: "Training",
      kind: "text",
      slot: "specifics",
      hint: "Service standards, assessments, onboarding new staff.",
    },
    {
      id: "budgeting",
      ask: "Which P&L lines were you responsible for?",
      label: "Budgeting",
      kind: "multi",
      slot: "skills",
      options: [
        "Revenue / sales",
        "Food cost",
        "Beverage cost",
        "Labour cost",
        "Full P&L",
        "CAPEX",
        "Purchasing",
        "Stocktaking",
      ],
      required: true,
    },
    {
      id: "reporting",
      ask: "Which systems did you report in?",
      label: "Reporting",
      kind: "multi",
      slot: "systems",
      options: [
        "Micros / Oracle",
        "iiko",
        "r_keeper",
        "Opera PMS",
        "Excel / Google Sheets",
        "Power BI",
        "In-house system",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
