import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры официанта — по списку из документа заказчика, раздел 1.1. */
export const waiter: Profession = {
  id: "waiter",
  title: "Waiter / Waitress",
  family: "service",
  blurb: "Обслуживание, sequence of service, вино, upselling.",
  levels: [
    "Commis de rang",
    "Waiter",
    "Senior Waiter",
    "Chef de rang",
    "Head Waiter",
    "Sommelier",
  ],
  questions: [
    {
      id: "level",
      ask: "Ваша последняя позиция в зале?",
      label: "Позиция",
      kind: "single",
      slot: "summary",
      options: [
        "Commis de rang",
        "Waiter",
        "Senior Waiter",
        "Chef de rang",
        "Head Waiter",
        "Sommelier",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "Сколько лет опыта в зале?",
      label: "Опыт",
      kind: "number",
      slot: "experience",
      unit: "лет",
      min: 0,
      max: 40,
      required: true,
    },
    {
      id: "venue_types",
      ask: "Какого типа были заведения?",
      label: "Типы заведений",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "section_size",
      ask: "Какую секцию вы вели — сколько столов на вас было?",
      label: "Столов в секции",
      kind: "number",
      slot: "scale",
      unit: "столов",
      min: 0,
      max: 60,
      required: true,
    },
    {
      id: "covers",
      ask: "Сколько covers обслуживали за смену?",
      label: "Covers за смену",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 1000,
      required: true,
    },
    {
      id: "pos_systems",
      ask: "На каких POS работали?",
      label: "POS-системы",
      kind: "multi",
      slot: "systems",
      options: [
        "Micros / Oracle Simphony",
        "Lightspeed",
        "Toast",
        "Square",
        "iiko",
        "r_keeper",
        "Poster",
        "Другая",
      ],
      required: true,
    },
    {
      id: "sequence_of_service",
      ask: "Какой стандарт сервиса вы вели — по шагам, как у вас было принято?",
      label: "Sequence of service",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "Надиктуйте своими словами: от встречи гостя до расчёта.",
    },
    {
      id: "wine_knowledge",
      ask: "Насколько уверенно вы в вине — от «знаю базово» до «вёл винную карту»?",
      label: "Wine knowledge",
      kind: "scale",
      slot: "skills",
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: "food_knowledge",
      ask: "А по кухне и меню — насколько глубоко разбираетесь?",
      label: "Food knowledge",
      kind: "scale",
      slot: "skills",
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: "upselling",
      ask: "Был ли на вас upselling, и как это измерялось?",
      label: "Upselling",
      kind: "text",
      slot: "specifics",
      hint: "Средний чек, доля десертов, аперитивы — если считали.",
    },
    {
      id: "service_styles",
      ask: "Какие стили подачи знаете?",
      label: "Стили подачи",
      kind: "multi",
      slot: "specifics",
      options: [
        "A la carte",
        "Silver service",
        "Russian service",
        "French service",
        "Buffet",
        "Banquet",
        "Room service",
        "Tasting menu",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
