import type { Profession } from "./types";
import { VENUE_TYPES, APPEARANCE, COMMON_TAIL } from "./universal";

/** Параметры официанта — по списку из документа заказчика, раздел 1.1. */
export const waiter: Profession = {
  id: "waiter",
  title: "Waiter / Waitress",
  family: "service",
  blurb: "Service, sequence of service, wine, upselling.",
  levels: [
    "Commis de rang",
    "Waiter",
    "Senior Waiter",
    "Chef de rang",
    "Head Waiter",
    "Sommelier",
  ],
  questions: [
    {
      id: "level",
      ask: "Your most recent front-of-house position?",
      label: "Position",
      kind: "single",
      slot: "summary",
      options: [
        "Commis de rang",
        "Waiter",
        "Senior Waiter",
        "Chef de rang",
        "Head Waiter",
        "Sommelier",
      ],
      required: true,
    },
    {
      id: "years",
      ask: "How many years of floor experience?",
      label: "Experience",
      kind: "number",
      slot: "experience",
      unit: "years",
      min: 0,
      max: 40,
      required: true,
    },
    {
      id: "venue_types",
      ask: "What kind of venues were they?",
      label: "Venue types",
      kind: "multi",
      slot: "specifics",
      options: VENUE_TYPES,
      required: true,
    },
    {
      id: "section_size",
      ask: "What section did you run: how many tables were yours?",
      label: "Tables in section",
      kind: "number",
      slot: "scale",
      unit: "tables",
      min: 0,
      max: 60,
      required: true,
    },
    {
      id: "covers",
      ask: "How many covers did you serve per shift?",
      label: "Covers per shift",
      kind: "number",
      slot: "scale",
      unit: "covers",
      min: 0,
      max: 1000,
      required: true,
    },
    {
      id: "pos_systems",
      ask: "Which POS systems have you used?",
      label: "POS systems",
      kind: "multi",
      slot: "systems",
      options: [
        "Micros / Oracle Simphony",
        "Lightspeed",
        "Toast",
        "Square",
        "iiko",
        "r_keeper",
        "Poster",
        "Other",
      ],
      required: true,
    },
    {
      id: "sequence_of_service",
      ask: "What service standard did you follow, step by step, as it was done at your place?",
      label: "Sequence of service",
      kind: "text",
      slot: "specifics",
      required: true,
      hint: "Dictate it in your own words: from greeting the guest to the bill.",
    },
    {
      id: "wine_knowledge",
      ask: "How confident are you with wine, from basics to running the wine list?",
      label: "Wine knowledge",
      kind: "scale",
      slot: "skills",
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: "food_knowledge",
      ask: "And how deep is your knowledge of the food and the menu?",
      label: "Food knowledge",
      kind: "scale",
      slot: "skills",
      min: 1,
      max: 5,
      required: true,
    },
    {
      id: "upselling",
      ask: "Was upselling on you, and how was it measured?",
      label: "Upselling",
      kind: "text",
      slot: "specifics",
      hint: "Average check, dessert share, aperitifs, if anyone counted.",
    },
    {
      id: "service_styles",
      ask: "Which service styles do you know?",
      label: "Service styles",
      kind: "multi",
      slot: "specifics",
      options: [
        "A la carte",
        "Silver service",
        "Russian service",
        "French service",
        "Buffet",
        "Banquet",
        "Room service",
        "Tasting menu",
      ],
    },
    ...APPEARANCE,
    ...COMMON_TAIL,
  ],
};
